services:
    - type: web
      plan: free
      name: mysite
      env: python
      buildCommand: "./build.sh"
      startCommand: "gunicorn mysite.wsgi:application"
      autoDeploy: false
      envVars:
          - key: SECRET_KEY
            generateValue: true
          - key: WEB_CONCURRENCY
            value: 4
